/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CHUCVU_BLL;
import BLL.QLNhanVienBLL;
import DTO.NhanVienDTO;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class Frm_QuanLyNhanVien extends javax.swing.JInternalFrame {
    DefaultTableModel model = new DefaultTableModel();
    QLNhanVienBLL QLNhanVien = new QLNhanVienBLL();
    CHUCVU_BLL QLChucVu = new CHUCVU_BLL();
    ArrayList<String> dsTenChucVu = new ArrayList<>();
    NhanVienDTO nv = new NhanVienDTO();
    Boolean onClickAdd = false;
    Boolean onClickUpdate = false;
    /**
     * Creates new form FM_QuanLyNhanVien
     */
    public Frm_QuanLyNhanVien() {
        initComponents();
        this.setVisible(true);
        ButtonGroup bG = new ButtonGroup();
        bG.add(radio_Nam);
        bG.add(radio_Nu);
        Load_Combobox_ChucVu();
        LoadData();
    }
    private void Load_Combobox_ChucVu()
    {
        dsTenChucVu = QLChucVu.getTenCV();
        cbo_ChucVu.removeAllItems();
        for (String item : dsTenChucVu)
            cbo_ChucVu.addItem(item);
    }
    private void LoadData() 
    {
        model.setColumnIdentifiers(QLNhanVien.listTitleNV());
        model.setRowCount(0);
        for (NhanVienDTO nv : QLNhanVien.showListNV_BLL()) 
        {
            model.addRow(new Object[]{
                nv.getMaNV(), QLNhanVien.GetChucVu(nv.getTaiKhoan()), nv.getTenNV(), nv.getGioiTinh(), nv.getDiaChi(), nv.getSdt(), nv.getTaiKhoan()});
        }
        JTable_NhanVien.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txt_MaNV = new javax.swing.JTextField();
        txt_TenNV = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        radio_Nam = new javax.swing.JRadioButton();
        radio_Nu = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txt_Sdt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txt_MatKhau = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_XNMatKhau = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_TaiKhoan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_DiaChi = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        cbo_ChucVu = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTable_NhanVien = new javax.swing.JTable();
        btn_Sua = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Luu = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1557, 815));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_MaNV.setEditable(false);
        txt_MaNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_TenNV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tên nhân viên:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Mã nhân viên:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Giới tính:");

        radio_Nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radio_Nam.setText("Nam");

        radio_Nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        radio_Nu.setText("Nữ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Số điện thoại:");

        txt_Sdt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(46, 46, 46)
                        .addComponent(txt_Sdt))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(radio_Nam)
                                .addGap(18, 18, 18)
                                .addComponent(radio_Nu))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_TenNV, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(txt_MaNV)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_TenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(radio_Nam)
                    .addComponent(radio_Nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txt_MatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Xác nhận mật khẩu:");

        txt_XNMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tài khoản:");

        txt_TaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Địa chỉ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu:");

        txtArea_DiaChi.setColumns(20);
        txtArea_DiaChi.setRows(5);
        jScrollPane1.setViewportView(txtArea_DiaChi);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Chức vụ:");

        cbo_ChucVu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_TaiKhoan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                            .addComponent(txt_XNMatKhau, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_MatKhau, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(cbo_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cbo_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_XNMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        JTable_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTable_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTable_NhanVien);

        btn_Sua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Them.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Luu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        btn_Huy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(422, 422, 422)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void ClearAllTxt()
    {
        txt_MaNV.setText("");
        txt_TenNV.setText("");
        txt_Sdt.setText("");
        txt_TaiKhoan.setText("");
        txt_MatKhau.setText("");
        txt_XNMatKhau.setText("");
        txtArea_DiaChi.setText("");
    }
    public Boolean checkAllTxt()
    {
        if(txt_MaNV.getText().equals("") || txt_TenNV.getText().equals("") || txt_Sdt.getText().equals("") || 
            txt_TaiKhoan.getText().equals("") || txt_MatKhau.getText().equals("") || txt_XNMatKhau.getText().equals("") || 
            txtArea_DiaChi.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đầy đủ thông tin", "Thông báo",2);
            return false;
        }
        return true;
    }
    private void SearchNV()
    {
        int index = JTable_NhanVien.getSelectedRow();
        NhanVienDTO nv = new NhanVienDTO();
        QLNhanVien.LoadNV(index, nv);
        txt_MaNV.setText(nv.getMaNV());
        txt_TenNV.setText(nv.getTenNV());
        if(nv.getGioiTinh().equals("Nam"))
            radio_Nam.setSelected(true);
        if(nv.getGioiTinh().equals("Nữ"))
            radio_Nu.setSelected(true);
        txtArea_DiaChi.setText(nv.getDiaChi());
        txt_Sdt.setText(nv.getSdt());
        txt_TaiKhoan.setText(nv.getTaiKhoan());
        txt_MatKhau.setText(nv.getMatKhau());
        txt_XNMatKhau.setText(nv.getMatKhau());
        cbo_ChucVu.setSelectedItem(QLNhanVien.GetChucVu(nv.getTaiKhoan()));
    }
    private void JTable_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_NhanVienMouseClicked
        SearchNV();
        btn_Xoa.setEnabled(true);
        btn_Sua.setEnabled(true);
    }//GEN-LAST:event_JTable_NhanVienMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        onClickUpdate = true;
        btn_Xoa.setEnabled(true);
        btn_Them.setEnabled(true);
    }//GEN-LAST:event_btn_SuaActionPerformed
    public String getMaNhanVien() {
        String maLoaiNuoc = "NV";
        int sl = QLNhanVien.getSoLuongNhanVien();
        sl += 1;
        if(sl < 10)
            maLoaiNuoc = "NV0" + sl;
        else
            maLoaiNuoc = "NV" + sl;
        return maLoaiNuoc;
    }
    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        onClickAdd = true;
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
        ClearAllTxt();
        txt_MaNV.setText(getMaNhanVien());
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa nhân viên này không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            String kq = QLNhanVien.deleteNV(txt_MaNV.getText());
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            model.setRowCount(0);
            LoadData();
            ClearAllTxt();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        if(checkAllTxt())
        {
            if(onClickAdd == true)
            {
                String gioiTinh = "";
                if(radio_Nam.isSelected() == true)
                gioiTinh = "Nam";
                if(radio_Nu.isSelected() == true)
                gioiTinh = "Nữ";
                NhanVienDTO nv = new NhanVienDTO(txt_MaNV.getText(), QLChucVu.GetMaChucVu(cbo_ChucVu.getSelectedItem().toString()), txt_TenNV.getText(), gioiTinh, txtArea_DiaChi.getText(), txt_Sdt.getText(), txt_TaiKhoan.getText(), txt_MatKhau.getText());
                String kq = QLNhanVien.themNV(nv);
                JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
                model.setRowCount(0);
                LoadData();
                onClickAdd = false;
            }
            if(onClickUpdate == true)
            {
                String gioiTinh = "";
                if(radio_Nam.isSelected() == true)
                gioiTinh = "Nam";
                if(radio_Nu.isSelected() == true)
                gioiTinh = "Nữ";
                NhanVienDTO nv = new NhanVienDTO(txt_MaNV.getText(), QLChucVu.GetMaChucVu(txt_MaNV.getText()), txt_TenNV.getText(), gioiTinh, txtArea_DiaChi.getText(), txt_Sdt.getText(), txt_TaiKhoan.getText(), txt_MatKhau.getText());
                String kq = QLNhanVien.upateNV(nv);
                JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
                model.setRowCount(0);
                LoadData();
                onClickUpdate = false; 
            }
        }
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        ClearAllTxt();
        btn_Them.setEnabled(true);
        txt_MaNV.setEnabled(true);
    }//GEN-LAST:event_btn_HuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_NhanVien;
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbo_ChucVu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radio_Nam;
    private javax.swing.JRadioButton radio_Nu;
    private javax.swing.JTextArea txtArea_DiaChi;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MatKhau;
    private javax.swing.JTextField txt_Sdt;
    private javax.swing.JTextField txt_TaiKhoan;
    private javax.swing.JTextField txt_TenNV;
    private javax.swing.JTextField txt_XNMatKhau;
    // End of variables declaration//GEN-END:variables
}
