/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import DTO.*;
import java.awt.Button;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import jdk.nashorn.internal.runtime.regexp.joni.EncodingHelper;

/**
 *
 * @author DELL
 */
public class Frm_QuanLyBan extends javax.swing.JFrame {

    /**
     * Creates new form Frm_QuanLyBan
     */
    JPanel chirl_panel = new JPanel();
    BAN_BLL ban_BLL = new BAN_BLL();
    HOADON_BLL hoadon_bll = new HOADON_BLL();

    ArrayList<JButton> lstButon = new ArrayList<JButton>();

    public Frm_QuanLyBan() {
        initComponents();
        LoadData();
        HienThiBan();
    }

    private void LoadData() {
        chirl_panel = new Panel_ChiTietHD_Ban();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
        panel_control_CTHD.setSize(930, 446);
        //LoadTrangThaiBan();
    }

    private void CapNhatTrangThaiBan(String _trangThai, JButton btn) {
        if (_trangThai.equals("trong")) {
            setTrangThaiTrong(btn);
        } else if (_trangThai.equals("datcho")) {
            setTrangThaiDaDat(btn);
        } else {
            setTrangThaiCoKhach(btn);
        }
    }

    private void HienThiBan() {
        ArrayList<BAN_DTO> lstBan = ban_BLL.showThongTinBan();
        int slban = lstBan.size();
        if (lstBan.size() != 0) {
            panel_HienThiBan.removeAll();
            panel_HienThiBan.setLayout(new GridLayout(0, 4, 10, 10));
            panel_HienThiBan.setSize(274, 444);
            for (BAN_DTO item : lstBan) {
                String _maBan = item.getMABAN();
                JButton btn = new JButton(item.getTENBAN());
                btn.setText(item.getTENBAN());
                btn.setName(_maBan);
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        LoadCT_HoaDon(item.getMABAN(), item.getTENBAN());
                        LoadTrangThaiBan();
                    }
                });
                btn.setSize(10, 10);
                lstButon.add(btn);
                panel_HienThiBan.add(btn);
            }
            panel_HienThiBan.revalidate();
            panel_HienThiBan.repaint();
        } else {
            JOptionPane.showConfirmDialog(null, "Không có dữ liệu bàn để hiển thị", "Thông báo hệ thống", JOptionPane.DEFAULT_OPTION);
        }
    }

    public void LoadTrangThaiBan() {
        for (JButton items : lstButon) {
            CapNhatTrangThaiBan(ban_BLL.getTrangThai(items.getName()), items);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel_HienThiBan = new javax.swing.JPanel();
        panel_control_CTHD = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));

        jLabel1.setBackground(new java.awt.Color(0, 255, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ BÀN");

        panel_HienThiBan.setBackground(new java.awt.Color(106, 166, 255));

        javax.swing.GroupLayout panel_HienThiBanLayout = new javax.swing.GroupLayout(panel_HienThiBan);
        panel_HienThiBan.setLayout(panel_HienThiBanLayout);
        panel_HienThiBanLayout.setHorizontalGroup(
            panel_HienThiBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        panel_HienThiBanLayout.setVerticalGroup(
            panel_HienThiBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        panel_control_CTHD.setBackground(new java.awt.Color(204, 255, 255));
        panel_control_CTHD.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_HienThiBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_control_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_control_CTHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_HienThiBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTrangThaiDaDat(JButton btn) {
        btn.setBackground(Color.YELLOW);
    }

    public void setTrangThaiTrong(JButton btn) {
        btn.setBackground(Color.GREEN);
    }

    public void setTrangThaiCoKhach(JButton btn) {
        btn.setBackground(Color.RED);
    }

    public void UpdateTrangThaiCoKhach(String maBan) {
        ban_BLL.CapNhatTrangThai(maBan, "hetcho");
        //LoadTrangThaiBan();
    }

    public void UpdateTrangThaiVangKhach(String maBan) {
        ban_BLL.CapNhatTrangThai(maBan, "trong");
        //LoadTrangThaiBan();
    }

    private void LoadCT_HoaDon(String _maBan, String _tenBan) {
        // LoadTrangThaiBan();
        Panel_ChiTietHD_Ban CT_HD_ban = new Panel_ChiTietHD_Ban();
        String MaBan = _maBan;
        String ttBan = _tenBan;
        CT_HD_ban.setTenBan(ttBan);
        String trangthai = ban_BLL.getTrangThai(MaBan);
        CT_HD_ban.SetMaBan(MaBan, trangthai);
        if (trangthai.equalsIgnoreCase("trong") == false) {
            CT_HD_ban.SetMaHoaDon(hoadon_bll.getMaHoaDonByBan(MaBan));
        }
        CT_HD_ban.LoadChiTietHoaDon();
        chirl_panel = CT_HD_ban;
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_QuanLyBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_HienThiBan;
    private javax.swing.JPanel panel_control_CTHD;
    // End of variables declaration//GEN-END:variables
}
