/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.PHIEUNHAP_BLL;
import Connect.Connect_DB;
import DTO.PHIEUNHAP_DTO;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author khanh
 */
public class Frm_PhieuNhap extends javax.swing.JInternalFrame {
    String _maPN="";
    DefaultTableModel tblModel_Phieu = new DefaultTableModel();
    PHIEUNHAP_BLL phieuBLL = new PHIEUNHAP_BLL();
    //PHIEUNHAP_DTO n = new PHIEUNHAP_DTO();
    ArrayList<PHIEUNHAP_DTO> lstPHIEU = new ArrayList<PHIEUNHAP_DTO>();
    /**
     * Creates new form Frm_PhieuNhap
     */
    public Frm_PhieuNhap() {
        initComponents();
        this.setVisible(true);
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_mancc = new javax.swing.JTextField();
        txt_ngaynhap = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_tongtien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_xuatPN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_maphieu = new javax.swing.JTextField();
        txt_manl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_dvt = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tennl = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_sl = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        txt_tenphieu = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        txt_manv = new javax.swing.JTextField();
        btn_huy = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_PN = new javax.swing.JTable();

        txt_mancc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_ngaynhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("TỔNG TIỀN: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mã Phiếu Nhập: ");

        txt_tongtien.setEditable(false);
        txt_tongtien.setBackground(new java.awt.Color(51, 255, 255));
        txt_tongtien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Mã Nguyên Liệu:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("(VND)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tên Nguyên Liệu:");

        btn_xuatPN.setBackground(new java.awt.Color(153, 0, 0));
        btn_xuatPN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_xuatPN.setText("XUẤT PHIẾU");
        btn_xuatPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xuatPNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SL:");

        txt_maphieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_maphieu.setText("P01");

        txt_manl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DVT:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Đơn giá:");

        txt_dvt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_gia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("TT:");

        txt_tt.setEditable(false);
        txt_tt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_tt.setForeground(new java.awt.Color(255, 0, 51));
        txt_tt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ttActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("(VND)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mã nhân viên:");

        txt_tennl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Tên Phiếu Nhập: ");

        txt_sl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mã NCC:");

        btn_add.setBackground(new java.awt.Color(255, 204, 204));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add.png"))); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Ngày nhập:");

        btn_delete.setBackground(new java.awt.Color(255, 204, 204));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_tenphieu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_update.setBackground(new java.awt.Color(255, 204, 204));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        txt_manv.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_huy.setBackground(new java.awt.Color(255, 204, 204));
        btn_huy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/huy.png"))); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        tbl_PN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_PN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PNMouseClicked(evt);
            }
        });
        tbl_PN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_PNKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_PN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_manl, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_manv, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_tenphieu, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_maphieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                                            .addComponent(txt_tennl))
                                        .addGap(45, 45, 45)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_mancc, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                            .addComponent(txt_ngaynhap)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(50, 50, 50)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel8))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_tt)
                                                    .addComponent(txt_tongtien))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel15)
                                                .addGap(33, 33, 33)
                                                .addComponent(btn_xuatPN)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(44, 44, 44))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_huy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(267, 267, 267)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(txt_maphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(txt_ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txt_tenphieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txt_manl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_mancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txt_tennl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_huy)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xuatPN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void SetMaPN(String maPN) 
    {
        _maPN = maPN;
        txt_maphieu.setText(maPN);
    }
    
    public void loadTable() {
        tblModel_Phieu.setRowCount(0);
        tblModel_Phieu.setColumnIdentifiers(phieuBLL.showTitle());
        lstPHIEU = phieuBLL.getALL();
        for (PHIEUNHAP_DTO items : lstPHIEU) {
            tblModel_Phieu.addRow(new Object[]{
                // MAPHIEUNHAP, TENPHIEUNHAP,NGAYNHAP, MANHANVIEN, MANHACUNGCAP , MANGUYENLIEU, TENNGUYENLIEU, SOLUONG, DVT, GIA, THANHTIEN, TONGTIEN;
                items.getMAPHIEUNHAP(), items.getTENPHIEUNHAP(), items.getNGAYNHAP(), items.getMANHANVIEN(), items.getMANHACUNGCAP(), items.getMANGUYENLIEU(), items.getTENNGUYENLIEU(), items.getSOLUONG(), items.getDVT(), items.getGIA(), items.getTHANHTIEN()
            });
        }
        tbl_PN.setModel(tblModel_Phieu);
    }
    
    private void btn_xuatPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xuatPNActionPerformed

        if(txt_maphieu.getText()!=null)
        {
            _maPN=txt_maphieu.getText();
            ResultSet kt = phieuBLL.XuatPN(_maPN);
            if (kt != null) {
                XuatReport(_maPN);
            } else {
                JOptionPane.showConfirmDialog(null, "Xuất Phiếu Thất bại", "Thông báo", JOptionPane.DEFAULT_OPTION);
            }
        }
        else
        {
            JOptionPane.showConfirmDialog(null, "Chưa có mã phiếu nhập !!!!!", "Thông báo", JOptionPane.DEFAULT_OPTION);
        }

    }//GEN-LAST:event_btn_xuatPNActionPerformed

    private void txt_ttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ttActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_ttActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        // tính thành tiền
        float tien=0;
        float gia=Float.valueOf(txt_gia.getText());
        float sl=Float.valueOf(txt_sl.getText());
        tien=gia*sl;
        txt_tt.setText(String.valueOf(tien));
        txt_tt.getText();

        String MAPHIEUNHAP, TENPHIEUNHAP, NGAYNHAP, MANHANVIEN, MANHACUNGCAP, MANGUYENLIEU, TENNGUYENLIEU, SOLUONG, DVT, GIA, THANHTIEN, TONGTIEN;

        MAPHIEUNHAP = txt_maphieu.getText();
        TENPHIEUNHAP = txt_tenphieu.getText();
        NGAYNHAP = txt_ngaynhap.getText();
        MANHANVIEN = txt_manv.getText();
        MANHACUNGCAP = txt_mancc.getText();
        MANGUYENLIEU = txt_manl.getText();
        TENNGUYENLIEU = txt_tennl.getText();
        SOLUONG = txt_sl.getText();
        DVT = txt_dvt.getText();
        GIA = txt_gia.getText();
        THANHTIEN=String.valueOf(tien);

        PHIEUNHAP_DTO pn = new PHIEUNHAP_DTO(MAPHIEUNHAP.toString().trim(), TENPHIEUNHAP.toString().trim(), NGAYNHAP.toString().trim(), MANHANVIEN.toString().trim(), MANHACUNGCAP.toString().trim(), MANGUYENLIEU.toString().trim(), TENNGUYENLIEU.toString().trim(), SOLUONG.toString().trim(), DVT.toString().trim(), GIA.toString().trim(), THANHTIEN.toString().trim());
        String kt = phieuBLL.insert_PN(pn);
        JOptionPane.showConfirmDialog(null, kt, "Thông báo", JOptionPane.DEFAULT_OPTION);

        loadTable();
        // do sau khi thêm phiếu -> mới tính đc tổng tiền bao nhiu từ table
        tinhtongtien();
        //loadTable();

    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:

        String MAPHIEUNHAP, TENPHIEUNHAP, NGAYNHAP, MANHANVIEN, MANHACUNGCAP, MANGUYENLIEU, TENNGUYENLIEU, SOLUONG, DVT, GIA, THANHTIEN, TONGTIEN;
        MAPHIEUNHAP = txt_maphieu.getText();
        String maNL = txt_manl.getText();
        if (MAPHIEUNHAP == null) {
            JOptionPane.showConfirmDialog(null, "Bạn chưa chọn MÃ PHIÉU để xóa", "Thông báo", JOptionPane.DEFAULT_OPTION);
        } else {
            String maPhieu = MAPHIEUNHAP;
            int check = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                int kt = phieuBLL.delete_PN(maPhieu, maNL);
                if (kt == 1) {
                    JOptionPane.showConfirmDialog(null, "Thành Công", "Thông báo", JOptionPane.DEFAULT_OPTION);
                    loadTable();
                    tinhtongtien();
                } else {
                    JOptionPane.showConfirmDialog(null, "Thất bại", "Thông báo", JOptionPane.DEFAULT_OPTION);
                }
            }
        }

    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        // tính thành tiền
        float tien=0;
        float gia=Float.valueOf(txt_gia.getText());
        float sl=Float.valueOf(txt_sl.getText());
        tien=gia*sl;
        txt_tt.setText(String.valueOf(tien));

        String MAPHIEUNHAP, TENPHIEUNHAP, NGAYNHAP, MANHANVIEN, MANHACUNGCAP, MANGUYENLIEU, TENNGUYENLIEU, SOLUONG, DVT, GIA, THANHTIEN, TONGTIEN;

        MAPHIEUNHAP = txt_maphieu.getText();
        TENPHIEUNHAP = txt_tenphieu.getText();
        NGAYNHAP = txt_ngaynhap.getText();
        MANHANVIEN = txt_manv.getText();
        MANHACUNGCAP = txt_mancc.getText();
        MANGUYENLIEU = txt_manl.getText();
        TENNGUYENLIEU = txt_tennl.getText();
        SOLUONG = txt_sl.getText();
        DVT = txt_dvt.getText();
        GIA = txt_gia.getText();
        THANHTIEN = txt_tt.getText();

        tinhtongtien();

        PHIEUNHAP_DTO pn = new PHIEUNHAP_DTO(MAPHIEUNHAP.toString().trim(), TENPHIEUNHAP.toString().trim(), NGAYNHAP.toString().trim(), MANHANVIEN.toString().trim(), MANHACUNGCAP.toString().trim(), MANGUYENLIEU.toString().trim(), TENNGUYENLIEU.toString().trim(), SOLUONG.toString().trim(), DVT.toString().trim(), GIA.toString().trim(), THANHTIEN.toString().trim());
        String kt = phieuBLL.Update_PN(pn);
        JOptionPane.showConfirmDialog(null, kt, "Thông báo", JOptionPane.DEFAULT_OPTION);

        loadTable(); tt();// thành tiền

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        txt_dvt.setText("");
        txt_gia.setText("");
        txt_mancc.setText("");
        txt_manl.setText("");
        txt_manv.setText("");
        txt_maphieu.setText("");
        txt_ngaynhap.setText("");
        txt_sl.setText("");
        txt_tennl.setText("");
        txt_tenphieu.setText("");
        txt_tt.setText("");
        txt_tongtien.setText("");
    }//GEN-LAST:event_btn_huyActionPerformed
    public void display(int select) {
        int vt = tbl_PN.getSelectedRow();
        txt_maphieu.setText(tbl_PN.getValueAt(vt, 0).toString());
        txt_tenphieu.setText(tbl_PN.getValueAt(vt, 1).toString());
        txt_ngaynhap.setText(tbl_PN.getValueAt(vt, 2).toString());
        txt_manv.setText(tbl_PN.getValueAt(vt, 3).toString());
        txt_mancc.setText(tbl_PN.getValueAt(vt, 4).toString());
        txt_manl.setText(tbl_PN.getValueAt(vt, 5).toString());
        txt_tennl.setText(tbl_PN.getValueAt(vt, 6).toString());
        txt_sl.setText(tbl_PN.getValueAt(vt, 7).toString());
        txt_dvt.setText(tbl_PN.getValueAt(vt, 8).toString());
        txt_gia.setText(tbl_PN.getValueAt(vt, 9).toString());
        txt_tt.setText(tbl_PN.getValueAt(vt, 10).toString());
        // txt_tongtien.setText(TOOL_TIP_TEXT_KEY);
    }
    private void tbl_PNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PNMouseClicked
        // TODO add your handling code here:
        int vt = tbl_PN.getSelectedRow();
        display(vt);
        //tt();
        tinhtongtien();
        // cập nhật lại thành tiền và tổng tiền vào DB
        String MAPHIEUNHAP, TENPHIEUNHAP, NGAYNHAP, MANHANVIEN, MANHACUNGCAP, MANGUYENLIEU, TENNGUYENLIEU, SOLUONG, DVT, GIA, THANHTIEN, TONGTIEN;

        MAPHIEUNHAP = txt_maphieu.getText();
        TENPHIEUNHAP = txt_tenphieu.getText();
        NGAYNHAP = txt_ngaynhap.getText();
        MANHANVIEN = txt_manv.getText();
        MANHACUNGCAP = txt_mancc.getText();
        MANGUYENLIEU = txt_manl.getText();
        TENNGUYENLIEU = txt_tennl.getText();
        SOLUONG = txt_sl.getText();
        DVT = txt_dvt.getText();
        GIA = txt_gia.getText();
        THANHTIEN = txt_tt.getText();
        TONGTIEN=txt_tongtien.getText();

        PHIEUNHAP_DTO pn = new PHIEUNHAP_DTO(MAPHIEUNHAP.toString().trim(), TENPHIEUNHAP.toString().trim(), NGAYNHAP.toString().trim(), MANHANVIEN.toString().trim(), MANHACUNGCAP.toString().trim(), MANGUYENLIEU.toString().trim(), TENNGUYENLIEU.toString().trim(), SOLUONG.toString().trim(), DVT.toString().trim(), GIA.toString().trim(), THANHTIEN.toString().trim(), TONGTIEN.toString().trim());
        String kt = phieuBLL.Update_PN(pn);
    }//GEN-LAST:event_tbl_PNMouseClicked
    public void tt()
    {
        float tien=0;
        float gia=Float.valueOf(txt_gia.getText());
        float sl=Float.valueOf(txt_sl.getText());
        tien=gia*sl;
        txt_tt.setText(String.valueOf(tien));         
    }
    
    public void tinhtongtien() {
        float sum = 0;
        String maPhieuNhap = txt_maphieu.getText();
        for (int i = 0; i < tbl_PN.getRowCount(); i++) {
            if (tbl_PN.getValueAt(i, 0).toString().equalsIgnoreCase(maPhieuNhap) == true) {
                sum += Float.valueOf(tbl_PN.getValueAt(i, 10).toString());
            }
        }
        txt_tongtien.setText(String.valueOf(sum));
        //tt();
    }
    
    public void XuatReport(String _mapn) {
        try {
            Connect_DB cn = new Connect_DB();
            Hashtable map = new Hashtable();            
            JasperReport rpt = JasperCompileManager.compileReport("D:/DoAnJava_PhanMemOrderCoffee/src/Report/rpt_NhapHang.jrxml");
            map.put("maPN", _mapn);            
            Connection con = cn.getCn();
            JasperPrint p = JasperFillManager.fillReport(rpt, map, con);
            JasperViewer.viewReport(p, false);
        } catch (JRException ex) {
            Logger.getLogger(Panel_ChiTietBan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tbl_PNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_PNKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            int selectedIndex = tbl_PN.getSelectedRow();
            display(selectedIndex);
        }
    }//GEN-LAST:event_tbl_PNKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_xuatPN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_PN;
    private javax.swing.JTextField txt_dvt;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_mancc;
    private javax.swing.JTextField txt_manl;
    private javax.swing.JTextField txt_manv;
    private javax.swing.JTextField txt_maphieu;
    private javax.swing.JTextField txt_ngaynhap;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_tennl;
    private javax.swing.JTextField txt_tenphieu;
    private javax.swing.JTextField txt_tongtien;
    private javax.swing.JTextField txt_tt;
    // End of variables declaration//GEN-END:variables
}
