/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.NGUYENLIEU_BLL;
import DTO.NguyenLieu_DTO;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class Frm_NguyenLieu extends javax.swing.JInternalFrame {
    DefaultTableModel tblModel_NguyenLieu = new DefaultTableModel();
    NGUYENLIEU_BLL nlBLL = new NGUYENLIEU_BLL();
    ArrayList<NguyenLieu_DTO> lstNL = new ArrayList<NguyenLieu_DTO>();
    /**
     * Creates new form Frm_NguyenLieu
     */
    public Frm_NguyenLieu() {
        initComponents();
        this.setVisible(true);
        loadTable();
    }
    public void loadTable()
    {
        tblModel_NguyenLieu.setRowCount(0);
        tblModel_NguyenLieu.setColumnIdentifiers(nlBLL.showTitle());
        lstNL = nlBLL.getALL();
        for (NguyenLieu_DTO items : lstNL) {
           tblModel_NguyenLieu.addRow(new Object[]{
                    items.getMANGUYENLIEU(), items.getTENNGUYENLIEU(), items.getSOLUONG(), items.getTONKHO(), items.getDVT()
                });
        }
        tbl_NL.setModel(tblModel_NguyenLieu);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_manl = new javax.swing.JTextField();
        txt_sl = new javax.swing.JTextField();
        txt_tennl = new javax.swing.JTextField();
        txt_dvt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        txt_tonkho = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Số lượng: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("DVT:");

        txt_manl.setEditable(false);
        txt_manl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_sl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_tennl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_dvt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tồn kho:");

        btn_delete.setBackground(new java.awt.Color(255, 204, 204));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        txt_tonkho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_update.setBackground(new java.awt.Color(255, 204, 204));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/update.png"))); // NOI18N
        btn_update.setText("Sửa");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        tbl_NL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_NL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NLMouseClicked(evt);
            }
        });
        tbl_NL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_NLKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_NL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mã Nguyên Liệu: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Tên Nguyên Liệu:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_manl, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                                            .addComponent(txt_tennl)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_sl, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                                            .addComponent(txt_dvt))))
                                .addGap(134, 134, 134)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 263, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_manl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tennl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dvt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txt_tonkho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_update))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void display(int select)
    {
        int vt=tbl_NL.getSelectedRow();
        //Vector vct = (Vetor)

        txt_manl.setText(tbl_NL.getValueAt(vt, 0).toString());
        txt_tennl.setText(tbl_NL.getValueAt(vt, 1).toString());
        txt_sl.setText(tbl_NL.getValueAt(vt, 2).toString());
        txt_tonkho.setText(tbl_NL.getValueAt(vt, 3).toString());
        txt_dvt.setText(tbl_NL.getValueAt(vt, 4).toString());
    }
    
    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        String ma, ten, sl, dvt, tonkho;
        ma=txt_manl.getText();

        if (ma==null) {
            JOptionPane.showConfirmDialog(null, "Bạn chưa chọn NCL để xóa", "Thông báo", JOptionPane.DEFAULT_OPTION);
        } else {
            String maNL = ma;
            int check = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn xóa không?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                int kt = nlBLL.delete_NL(maNL);
                if (kt == 1) {
                    JOptionPane.showConfirmDialog(null, "Thành Công", "Thông báo", JOptionPane.DEFAULT_OPTION);
                    loadTable();
                } else {
                    JOptionPane.showConfirmDialog(null, "Thất bại", "Thông báo", JOptionPane.DEFAULT_OPTION);
                }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        String ma, ten, sl, dvt, tonkho;
        ma=txt_manl.getText();
        ten=txt_tennl.getText();
        sl=txt_sl.getText();
        tonkho=txt_tonkho.getText();
        dvt=txt_dvt.getText();

        NguyenLieu_DTO nl = new NguyenLieu_DTO(ma.toString().trim(), ten.toString().trim(), sl.toString().trim(), tonkho.toString().trim(), dvt.toString().trim());
        String kt = nlBLL.Update_NL(nl);
        JOptionPane.showConfirmDialog(null, kt, "Thông báo", JOptionPane.DEFAULT_OPTION);
        loadTable();

    }//GEN-LAST:event_btn_updateActionPerformed

    private void tbl_NLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NLMouseClicked
        // TODO add your handling code here:
        int vt=tbl_NL.getSelectedRow();
        display(vt);

    }//GEN-LAST:event_tbl_NLMouseClicked

    private void tbl_NLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_NLKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP || evt.getKeyCode()==KeyEvent.VK_DOWN)
        {
            int selectedIndex= tbl_NL.getSelectedRow();
            display(selectedIndex);
        }
    }//GEN-LAST:event_tbl_NLKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_NL;
    private javax.swing.JTextField txt_dvt;
    private javax.swing.JTextField txt_manl;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_tennl;
    private javax.swing.JTextField txt_tonkho;
    // End of variables declaration//GEN-END:variables
}
