/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import BLL.LOAITHUCUONG_BLL;
import BLL.THUCUONG_BLL;
import DTO.THUCUONG_DTO;
import DTO.LOAITHUCUONG_DTO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author khanh
 */
public class Frm_DanhSachNuoc extends javax.swing.JInternalFrame {
    LOAITHUCUONG_BLL QLLoaiNuoc = new LOAITHUCUONG_BLL();
    THUCUONG_BLL QLNuoc = new THUCUONG_BLL();
    ArrayList<THUCUONG_DTO> dsNuoc = new ArrayList<>();
    ArrayList<String> dsTenLoaiNuoc = new ArrayList<>();
    DefaultListModel<String> modelList = new DefaultListModel<>();
    DefaultTableModel modelNuoc = new DefaultTableModel();
    Boolean OnClickAdd = false;
    Boolean OnClickUpdate = false;
    Boolean OnClickAddNuoc = false;
    Boolean OnClickUpdateNuoc = false;
    /**
     * Creates new form QuanLyMonAn
     */
    public Frm_DanhSachNuoc() {
        initComponents();
        loadListLoaiNuoc();
        Load_Combobox_TenLoaiNuoc();
        LoadDataThucUong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTable_Nuoc = new javax.swing.JTable();
        btn_LuuNuoc = new javax.swing.JButton();
        btn_HuyNuoc = new javax.swing.JButton();
        btn_ThemNuoc = new javax.swing.JButton();
        btn_XoaNuoc = new javax.swing.JButton();
        btn_SuaNuoc = new javax.swing.JButton();
        btn_TimKiem = new javax.swing.JButton();
        txt_TenNuocCanTim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listLoaiNuoc = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        txtMaLoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        btn_Luu = new javax.swing.JButton();
        btn_Huy = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_MaNuoc = new javax.swing.JTextField();
        txt_TenNuoc = new javax.swing.JTextField();
        txt_DonGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbo_TenLoaiNuoc = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_Size = new javax.swing.JTextField();
        txt_TrangThai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setResizable(true);
        setMaximumSize(new java.awt.Dimension(974, 573));
        setMinimumSize(new java.awt.Dimension(974, 573));
        setPreferredSize(new java.awt.Dimension(1557, 815));
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DANH SÁCH THỨC UỐNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách thức uống", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        JTable_Nuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTable_Nuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTable_NuocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTable_Nuoc);

        btn_LuuNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_LuuNuoc.setText("Lưu");
        btn_LuuNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuNuocActionPerformed(evt);
            }
        });

        btn_HuyNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_HuyNuoc.setText("Hủy");
        btn_HuyNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyNuocActionPerformed(evt);
            }
        });

        btn_ThemNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ThemNuoc.setText("Thêm");
        btn_ThemNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemNuocActionPerformed(evt);
            }
        });

        btn_XoaNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XoaNuoc.setText("Xóa");
        btn_XoaNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaNuocActionPerformed(evt);
            }
        });

        btn_SuaNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_SuaNuoc.setText("Sửa");
        btn_SuaNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaNuocActionPerformed(evt);
            }
        });

        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        txt_TenNuocCanTim.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_HuyNuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_SuaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_ThemNuoc))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_XoaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btn_LuuNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txt_TenNuocCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimKiem)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XoaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SuaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LuuNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_HuyNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_TenNuocCanTim, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại nước", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        listLoaiNuoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listLoaiNuoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLoaiNuocMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listLoaiNuoc);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tên loại:");

        btn_Them.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        txtMaLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMaLoai.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Mã loại:");

        txtTenLoai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btn_Luu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Luu.setText("Lưu");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });

        btn_Huy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Huy.setText("Hủy");
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Luu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaLoai)
                                    .addComponent(txtTenLoai)))
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Luu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mã thức uống:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Tên thức uống:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Đơn giá:");

        txt_MaNuoc.setEditable(false);
        txt_MaNuoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TenNuoc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_DonGia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tên loại:");

        cbo_TenLoaiNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Size:");

        txt_Size.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txt_TrangThai.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Trạng thái:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaNuoc)
                            .addComponent(cbo_TenLoaiNuoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(469, 469, 469))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(418, 418, 418)
                                .addComponent(jLabel1))
                            .addComponent(jLabel10))
                        .addContainerGap(461, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(98, 98, 98)
                                .addComponent(txt_DonGia))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(39, 39, 39)
                                .addComponent(txt_TenNuoc))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Size)
                                    .addComponent(txt_TrangThai))))
                        .addGap(469, 469, 469))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbo_TenLoaiNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_MaNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_TenNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_TrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadListLoaiNuoc()
    {
        for (String tenLoaiNuoc : QLLoaiNuoc.getTenLoai()) 
        {
            modelList.addElement(tenLoaiNuoc);
        }
        listLoaiNuoc.setModel(modelList);
    }
    
    private void Load_Combobox_TenLoaiNuoc()
    {
        dsTenLoaiNuoc = QLLoaiNuoc.getTenLoai();
        cbo_TenLoaiNuoc.removeAllItems();
        for (String item : dsTenLoaiNuoc)
            cbo_TenLoaiNuoc.addItem(item);
    }
    
    private void LoadDataThucUong()
    {
        modelNuoc.setColumnIdentifiers(QLNuoc.showTitle());
        modelNuoc.setRowCount(0);
        for (THUCUONG_DTO nuoc : QLNuoc.getALL()) 
        {
            modelNuoc.addRow(new Object[]{
                nuoc.getMANUOC(), nuoc.getTENNUOC(), nuoc.getSIZE(), nuoc.getGIA()});
        }
        JTable_Nuoc.setModel(modelNuoc);
    }
    
    private void SearchLoaiNuoc()
    {
        txtTenLoai.setText(listLoaiNuoc.getSelectedValue());
        txtMaLoai.setText(QLLoaiNuoc.getMaLoai(listLoaiNuoc.getSelectedValue()));
    }
    
    private void listLoaiNuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLoaiNuocMouseClicked
        SearchLoaiNuoc();
    }//GEN-LAST:event_listLoaiNuocMouseClicked
    
    public String getMaLoaiThucUong() {
        String maLoaiNuoc = "L";
        int sl = QLLoaiNuoc.getSoLuongLoai();
        sl += 1;
        if(sl < 10)
            maLoaiNuoc = "L00" + sl;
        else
            maLoaiNuoc = "L0" + sl;
        return maLoaiNuoc;
    }
    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        OnClickAdd = true;
        txtTenLoai.setText("");
        txtMaLoai.setText(getMaLoaiThucUong());
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa loại thức uống này không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            String kq = QLLoaiNuoc.deleteLoaiNuoc(txtMaLoai.getText());
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            modelList.removeAllElements();
            loadListLoaiNuoc();
            btn_Them.setEnabled(true);
            btn_Sua.setEnabled(true);
            btn_Xoa.setEnabled(true);
            txtMaLoai.setText("");
            txtTenLoai.setText("");
            Load_Combobox_TenLoaiNuoc();
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        if(OnClickAdd == true)
        {
            LOAITHUCUONG_DTO nc = new LOAITHUCUONG_DTO(txtMaLoai.getText(), txtTenLoai.getText());
            String kq = QLLoaiNuoc.themLoaiNuoc(nc);
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            modelList.removeAllElements();
            loadListLoaiNuoc();
            Load_Combobox_TenLoaiNuoc();
            OnClickAdd = false;
        }
        if(OnClickUpdate == true)
        {
            LOAITHUCUONG_DTO nc = new LOAITHUCUONG_DTO(txtMaLoai.getText(), txtTenLoai.getText());
            String kq = QLLoaiNuoc.updateLoaiNuoc(nc);
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            modelList.removeAllElements();
            loadListLoaiNuoc();
            Load_Combobox_TenLoaiNuoc();
            OnClickUpdate = false;
        }
        btn_Them.setEnabled(true);
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        btn_Them.setEnabled(true);
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
        txtMaLoai.setText("");
        txtTenLoai.setText("");
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_LuuNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuNuocActionPerformed
       if(OnClickAddNuoc == true)
        {
            String maLoaiNuoc = QLLoaiNuoc.getMaLoai(cbo_TenLoaiNuoc.getSelectedItem().toString());
            float gia = Float.parseFloat(txt_DonGia.getText());
            THUCUONG_DTO nc = new THUCUONG_DTO(txt_MaNuoc.getText(), maLoaiNuoc, txt_TenNuoc.getText(), txt_Size.getText(), txt_TrangThai.getText(), gia);
            String kq = QLNuoc.themNuoc(nc);
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            modelNuoc.setRowCount(0);
            LoadDataThucUong();
            OnClickAddNuoc = false;
        }
        if(OnClickUpdateNuoc == true)
        {
            String maLoaiNuoc = QLLoaiNuoc.getMaLoai(cbo_TenLoaiNuoc.getSelectedItem().toString());
            float gia = Float.parseFloat(txt_DonGia.getText());
            THUCUONG_DTO nc = new THUCUONG_DTO(txt_MaNuoc.getText(), maLoaiNuoc, txt_TenNuoc.getText(), txt_Size.getText(), txt_TrangThai.getText(), gia);
            String kq = QLNuoc.updateNuoc(nc);
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            modelNuoc.setRowCount(0);
            LoadDataThucUong();
            OnClickUpdateNuoc = false;
        }
        btn_ThemNuoc.setEnabled(true);
        btn_SuaNuoc.setEnabled(true);
        btn_XoaNuoc.setEnabled(true);
        txt_MaNuoc.setText("");
        txt_TenNuoc.setText("");
        txt_DonGia.setText("");
        txt_Size.setText("");
        txt_TrangThai.setText("");
    }//GEN-LAST:event_btn_LuuNuocActionPerformed

    private void btn_HuyNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyNuocActionPerformed
        txt_MaNuoc.setText("");
        txt_TenNuoc.setText("");
        txt_DonGia.setText("");
        txt_Size.setText("");
        txt_TrangThai.setText("");
    }//GEN-LAST:event_btn_HuyNuocActionPerformed
    
    public String getMaThucUong() {
        String maLoaiNuoc = "N";
        int sl = QLNuoc.getSoLuongNuoc();
        sl += 1;
        if(sl < 10)
            maLoaiNuoc = "N00" + sl;
        else
            maLoaiNuoc = "N0" + sl;
        return maLoaiNuoc;
    }
    private void btn_ThemNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemNuocActionPerformed
        OnClickAddNuoc = true;
        txt_MaNuoc.setText(getMaThucUong());
        btn_SuaNuoc.setEnabled(false);
        btn_XoaNuoc.setEnabled(false);
    }//GEN-LAST:event_btn_ThemNuocActionPerformed

    private void btn_XoaNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaNuocActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa thức uống này không?", "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            String kq = QLNuoc.deleteNuoc(txt_MaNuoc.getText());
            JOptionPane.showConfirmDialog(null, kq, "Oops...", JOptionPane.DEFAULT_OPTION);
            modelNuoc.setRowCount(0);
            LoadDataThucUong();
            btn_ThemNuoc.setEnabled(true);
            btn_SuaNuoc.setEnabled(true);
            btn_XoaNuoc.setEnabled(true);
            txt_MaNuoc.setText("");
            txt_TenNuoc.setText("");
            txt_DonGia.setText("");
            txt_Size.setText("");
            txt_TrangThai.setText("");
        }
    }//GEN-LAST:event_btn_XoaNuocActionPerformed
    
    private void SearchNuoc()
    {
        int index = JTable_Nuoc.getSelectedRow();
        THUCUONG_DTO nuoc = new THUCUONG_DTO();
        QLNuoc.LoadNuoc(index, nuoc);
        cbo_TenLoaiNuoc.setSelectedItem(QLLoaiNuoc.GetTenLoaiNuoc(QLNuoc.GetMaLoaiNuoc(nuoc.getMANUOC())));
        txt_MaNuoc.setText(nuoc.getMANUOC());
        txt_TenNuoc.setText(nuoc.getTENNUOC());
        txt_DonGia.setText(nuoc.getGIA() + "");
        txt_Size.setText(nuoc.getSIZE());
        txt_TrangThai.setText(QLNuoc.GetTrangThai(nuoc.getMANUOC()));
    }
    private void JTable_NuocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTable_NuocMouseClicked
        SearchNuoc();
    }//GEN-LAST:event_JTable_NuocMouseClicked

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        OnClickUpdate = true;
        btn_Them.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_SuaNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaNuocActionPerformed
       OnClickUpdateNuoc = true;
       btn_ThemNuoc.setEnabled(false);
       btn_XoaNuoc.setEnabled(false);
    }//GEN-LAST:event_btn_SuaNuocActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        if(txt_TenNuocCanTim.getText().equals(""))
        {
            JOptionPane.showConfirmDialog(null, "Hãy nhập tên nước cần tìm!", "Oops...", JOptionPane.DEFAULT_OPTION);
            return;
        }
        String announ = QLNuoc.CheckExist(txt_TenNuocCanTim.getText());
        JOptionPane.showConfirmDialog(null, announ, "Oops...", JOptionPane.DEFAULT_OPTION);
        int rs = QLNuoc.SearchNuoc(txt_TenNuocCanTim.getText());
        JTable_Nuoc.setRowSelectionInterval(rs, rs);
        SearchNuoc();
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable_Nuoc;
    private javax.swing.JButton btn_Huy;
    private javax.swing.JButton btn_HuyNuoc;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JButton btn_LuuNuoc;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_SuaNuoc;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_ThemNuoc;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaNuoc;
    private javax.swing.JComboBox<String> cbo_TenLoaiNuoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listLoaiNuoc;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_MaNuoc;
    private javax.swing.JTextField txt_Size;
    private javax.swing.JTextField txt_TenNuoc;
    private javax.swing.JTextField txt_TenNuocCanTim;
    private javax.swing.JTextField txt_TrangThai;
    // End of variables declaration//GEN-END:variables
}
