/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package GUI;

import BLL.QLNhanVienBLL;
import DTO.NhanVienDTO;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luu Quang Khai
 */
public class Frm_QuanLy extends javax.swing.JFrame {
    QLNhanVienBLL QLNhanVien = new QLNhanVienBLL();
    NhanVienDTO nv = new NhanVienDTO();
    private String MaNhanVien;
    
    String tk, chucvu;
    public void getChucVu(String tk) {
        this.tk = tk;
        this.chucvu = QLNhanVien.GetChucVu(tk);
        lbl_ChucVu.setText(chucvu);
        if(chucvu.equalsIgnoreCase("NHÂN VIÊN"))
        {
            btnQuanLyNuoc.setVisible(false);
            btn_QuanLyNhapHang.setVisible(false);
            btn_ThongKeHoaDon.setVisible(false);
            btn_QuanLyNhanVien.setVisible(false);
        }
    }
    /**
     * Creates new form GiaoDien
     */
    public Frm_QuanLy() {
        initComponents();
        this.setLocationRelativeTo(null);
        btn_nhacc.setVisible(false);
        btn_nguyenlieu.setVisible(false);
        btn_phieunhap.setVisible(false);
        btn_QuayLai.setVisible(false);
        desktopPane.setSize(1617, 815);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        panel_ChucNang = new javax.swing.JPanel();
        btnQuanLyNuoc = new javax.swing.JButton();
        btnGoiMon = new javax.swing.JButton();
        btn_QuanLyNhanVien = new javax.swing.JButton();
        btn_QuanLyNhapHang = new javax.swing.JButton();
        btn_ThongKeHoaDon = new javax.swing.JButton();
        btn_nhacc = new javax.swing.JButton();
        btn_nguyenlieu = new javax.swing.JButton();
        btn_phieunhap = new javax.swing.JButton();
        btn_QuayLai = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_Quyen = new javax.swing.JLabel();
        btn_ThongTinCaNhan = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        lbl_ChucVu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1181, 674));

        desktopPane.setBackground(new java.awt.Color(153, 255, 153));
        desktopPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giao diện", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        desktopPane.setPreferredSize(new java.awt.Dimension(1181, 674));

        panel_ChucNang.setBackground(new java.awt.Color(153, 255, 153));
        panel_ChucNang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        btnQuanLyNuoc.setBackground(new java.awt.Color(255, 255, 255));
        btnQuanLyNuoc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnQuanLyNuoc.setText("Quản lý thức uống");
        btnQuanLyNuoc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQuanLyNuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNuocActionPerformed(evt);
            }
        });

        btnGoiMon.setBackground(new java.awt.Color(255, 255, 255));
        btnGoiMon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGoiMon.setText("Gọi món");
        btnGoiMon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGoiMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoiMonActionPerformed(evt);
            }
        });

        btn_QuanLyNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        btn_QuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_QuanLyNhanVien.setText("Quản lý nhân viên");
        btn_QuanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyNhanVienActionPerformed(evt);
            }
        });

        btn_QuanLyNhapHang.setBackground(new java.awt.Color(255, 255, 255));
        btn_QuanLyNhapHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_QuanLyNhapHang.setText("Quản lý nhập hàng");
        btn_QuanLyNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QuanLyNhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuanLyNhapHangActionPerformed(evt);
            }
        });

        btn_ThongKeHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThongKeHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ThongKeHoaDon.setText("Thống kê hóa đơn");
        btn_ThongKeHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_ThongKeHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeHoaDonActionPerformed(evt);
            }
        });

        btn_nhacc.setBackground(new java.awt.Color(255, 255, 255));
        btn_nhacc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_nhacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhacungcap.png"))); // NOI18N
        btn_nhacc.setText("Nhà cung cấp");
        btn_nhacc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhaccActionPerformed(evt);
            }
        });

        btn_nguyenlieu.setBackground(new java.awt.Color(255, 255, 255));
        btn_nguyenlieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_nguyenlieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nguyenlieu.png"))); // NOI18N
        btn_nguyenlieu.setText("Nguyên liệu");
        btn_nguyenlieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nguyenlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nguyenlieuActionPerformed(evt);
            }
        });

        btn_phieunhap.setBackground(new java.awt.Color(255, 255, 255));
        btn_phieunhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_phieunhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phieunhaphang.png"))); // NOI18N
        btn_phieunhap.setText("Phiếu nhập hàng");
        btn_phieunhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_phieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phieunhapActionPerformed(evt);
            }
        });

        btn_QuayLai.setBackground(new java.awt.Color(255, 255, 255));
        btn_QuayLai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_QuayLai.setText("Quay lại");
        btn_QuayLai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ChucNangLayout = new javax.swing.GroupLayout(panel_ChucNang);
        panel_ChucNang.setLayout(panel_ChucNangLayout);
        panel_ChucNangLayout.setHorizontalGroup(
            panel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ThongKeHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_QuanLyNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGoiMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuanLyNuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_QuanLyNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nhacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nguyenlieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phieunhap, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(btn_QuayLai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_ChucNangLayout.setVerticalGroup(
            panel_ChucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ChucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGoiMon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuanLyNuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QuanLyNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ThongKeHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_nhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_nguyenlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_phieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_QuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin cá nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đăng nhập với quyền:");

        lbl_Quyen.setBackground(new java.awt.Color(255, 51, 51));
        lbl_Quyen.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_Quyen.setForeground(new java.awt.Color(255, 51, 51));

        btn_ThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThongTinCaNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_ThongTinCaNhan.setText("Thông tin cá nhân");
        btn_ThongTinCaNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinCaNhanActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 255, 255));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(51, 51, 51));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lbl_ChucVu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ChucVu.setForeground(new java.awt.Color(204, 0, 51));
        lbl_ChucVu.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbl_Quyen))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 768, Short.MAX_VALUE)
                .addComponent(btn_ThongTinCaNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDangXuat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_Quyen)
                    .addComponent(btn_ThongTinCaNhan)
                    .addComponent(btnDangXuat)
                    .addComponent(btnThoat)
                    .addComponent(lbl_ChucVu))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_ChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_ChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1880, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyNuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNuocActionPerformed
        desktopPane.removeAll();
        JInternalFrame gui = new Frm_DanhSachNuoc();
        gui.setSize(1617, 815);
        desktopPane.add(gui);
    }//GEN-LAST:event_btnQuanLyNuocActionPerformed

    private void btnGoiMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoiMonActionPerformed
        desktopPane.removeAll();
        JInternalFrame gui = new Frm_QuanLyBan();
        gui.setSize(1617, 815);
        desktopPane.add(gui);
    }//GEN-LAST:event_btnGoiMonActionPerformed

    private void btn_QuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyNhanVienActionPerformed
        desktopPane.removeAll();
        JInternalFrame gui = new Frm_QuanLyNhanVien();
        gui.setSize(1617, 815);
        desktopPane.add(gui);
    }//GEN-LAST:event_btn_QuanLyNhanVienActionPerformed

    private void btn_ThongTinCaNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinCaNhanActionPerformed
        Frm_ThongTinCaNhan frm = new Frm_ThongTinCaNhan(this, rootPaneCheckingEnabled);
        boolean isOK = true;
        String taikhoan = "";
        try {
            taikhoan = tk;
        } catch (Exception e) {
            isOK = false;
        }
        if(isOK) {
            frm.getTaiKhoan(taikhoan);
            this.dispose();
        }
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ThongTinCaNhanActionPerformed

    private void btn_QuanLyNhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuanLyNhapHangActionPerformed
       desktopPane.setSize(1617, 815);
       desktopPane.removeAll();
       btnGoiMon.setVisible(false);
       btnQuanLyNuoc.setVisible(false);
       btn_ThongKeHoaDon.setVisible(false);
       btn_QuanLyNhanVien.setVisible(false);
       btn_QuanLyNhapHang.setVisible(false);
       btn_nhacc.setVisible(true);
       btn_nguyenlieu.setVisible(true);
       btn_phieunhap.setVisible(true);
       btn_QuayLai.setVisible(true);
    }//GEN-LAST:event_btn_QuanLyNhapHangActionPerformed

    private void btn_ThongKeHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeHoaDonActionPerformed
        desktopPane.removeAll();
        JInternalFrame gui = new Frm_ThongKe();
        gui.setSize(1617, 815);
        desktopPane.add(gui);
    }//GEN-LAST:event_btn_ThongKeHoaDonActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int n = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất ?", "Đăng xuất",JOptionPane.YES_NO_OPTION);
        if( n == JOptionPane.YES_OPTION)
        {
            Frm_DangNhap dn = new Frm_DangNhap();
            dn.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btn_nhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhaccActionPerformed
       desktopPane.removeAll();
       JInternalFrame gui = new Frm_NhaCungCap();
       gui.setSize(1557, 815);
       desktopPane.add(gui);
    }//GEN-LAST:event_btn_nhaccActionPerformed

    private void btn_nguyenlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nguyenlieuActionPerformed
       desktopPane.removeAll();
       JInternalFrame gui = new Frm_NguyenLieu();
       gui.setSize(1557, 815);
       desktopPane.add(gui);
    }//GEN-LAST:event_btn_nguyenlieuActionPerformed

    private void btn_phieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phieunhapActionPerformed
       desktopPane.removeAll();
       JInternalFrame gui = new Frm_PhieuNhap();
       gui.setSize(1557, 815);
       desktopPane.add(gui);
    }//GEN-LAST:event_btn_phieunhapActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    }//GEN-LAST:event_formWindowOpened

    private void btn_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuayLaiActionPerformed
       desktopPane.removeAll();
       btnGoiMon.setVisible(true);
       btnQuanLyNuoc.setVisible(true);
       btn_ThongKeHoaDon.setVisible(true);
       btn_QuanLyNhanVien.setVisible(true);
       btn_QuanLyNhapHang.setVisible(true);
       btn_nhacc.setVisible(false);
       btn_nguyenlieu.setVisible(false);
       btn_phieunhap.setVisible(false);
       btn_QuayLai.setVisible(false);
    }//GEN-LAST:event_btn_QuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_QuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnGoiMon;
    private javax.swing.JButton btnQuanLyNuoc;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btn_QuanLyNhanVien;
    private javax.swing.JButton btn_QuanLyNhapHang;
    private javax.swing.JButton btn_QuayLai;
    private javax.swing.JButton btn_ThongKeHoaDon;
    private javax.swing.JButton btn_ThongTinCaNhan;
    private javax.swing.JButton btn_nguyenlieu;
    private javax.swing.JButton btn_nhacc;
    private javax.swing.JButton btn_phieunhap;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_ChucVu;
    private javax.swing.JLabel lbl_Quyen;
    private javax.swing.JPanel panel_ChucNang;
    // End of variables declaration//GEN-END:variables

}
