/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import DTO.*;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;
import jdk.nashorn.internal.runtime.regexp.joni.EncodingHelper;

/**
 *
 * @author DELL
 */
public class Frm_QuanLyBan extends javax.swing.JFrame {

    /**
     * Creates new form Frm_QuanLyBan
     */
    JPanel chirl_panel = new JPanel();
    BAN_BLL ban_BLL = new BAN_BLL();
    HOADON_BLL hoadon_bll = new HOADON_BLL();

    public Frm_QuanLyBan() {
        initComponents();
        LoadData();
        LoadTrangThaiBan();
    }

    private void LoadData() {
        chirl_panel = new Panel_ChiTietHD_Ban();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
        panel_control_CTHD.setSize(930, 446);
    }

    public void LoadTrangThaiBan() {
        for (BAN_DTO items : ban_BLL.showThongTinBan()) {
            switch (items.getMABAN()) {

                case "B001":
                    String trangthaitemp = items.getTRANGTHAI();
                    if (items.getTRANGTHAI().equals("trong")) {
                        setTrangThaiTrong(btn_Ban01);
                    } else if (items.getTRANGTHAI().equals("datcho")) {
                        setTrangThaiDaDat(btn_Ban01);
                    } else {
                        setTrangThaiCoKhach(btn_Ban01);
                    }
                    break;
                case "B002":
                    trangthaitemp = items.getTRANGTHAI();
                    if (items.getTRANGTHAI().equals("trong")) {
                        setTrangThaiTrong(btn_Ban02);
                    } else if (items.getTRANGTHAI().equals("datcho")) {
                        setTrangThaiDaDat(btn_Ban02);
                    } else {
                        setTrangThaiCoKhach(btn_Ban02);
                    }
                    break;
                case "B003":
                    trangthaitemp = items.getTRANGTHAI();
                    if (items.getTRANGTHAI().equals("trong")) {
                        setTrangThaiTrong(btn_Ban03);
                    } else if (items.getTRANGTHAI().equals("datcho")) {
                        setTrangThaiDaDat(btn_Ban03);
                    } else {
                        setTrangThaiCoKhach(btn_Ban03);
                    }
                    break;
                case "B004":
                    trangthaitemp = items.getTRANGTHAI();
                    if (items.getTRANGTHAI().equals("trong")) {
                        setTrangThaiTrong(btn_Ban04);
                    } else if (items.getTRANGTHAI().equals("datcho")) {
                        setTrangThaiDaDat(btn_Ban04);
                    } else {
                        setTrangThaiCoKhach(btn_Ban04);
                    }
                    break;
                case "B005":
                    trangthaitemp = items.getTRANGTHAI();
                    if (items.getTRANGTHAI().equals("trong")) {
                        setTrangThaiTrong(btn_Ban05);
                    } else if (items.getTRANGTHAI().equals("datcho")) {
                        setTrangThaiDaDat(btn_Ban05);
                    } else {
                        setTrangThaiCoKhach(btn_Ban05);
                    }
                    break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_Ban02 = new javax.swing.JButton();
        btn_Ban01 = new javax.swing.JButton();
        btn_Ban03 = new javax.swing.JButton();
        btn_Loading = new javax.swing.JButton();
        btn_Ban05 = new javax.swing.JButton();
        btn_Ban04 = new javax.swing.JButton();
        panel_control_CTHD = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("QUẢN LÝ BÀN");

        jPanel1.setBackground(new java.awt.Color(106, 166, 255));

        btn_Ban02.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ban02.setText("BÀN 02");
        btn_Ban02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban02ActionPerformed(evt);
            }
        });

        btn_Ban01.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ban01.setText("BÀN 01");
        btn_Ban01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban01ActionPerformed(evt);
            }
        });

        btn_Ban03.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ban03.setText("BÀN 03");
        btn_Ban03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban03ActionPerformed(evt);
            }
        });

        btn_Loading.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Loading.setText("làm mới");
        btn_Loading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LoadingActionPerformed(evt);
            }
        });

        btn_Ban05.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ban05.setText("BÀN 05");
        btn_Ban05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban05ActionPerformed(evt);
            }
        });

        btn_Ban04.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_Ban04.setText("BÀN 04");
        btn_Ban04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban04ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Ban03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Ban04))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Ban01)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Ban02))
                    .addComponent(btn_Ban05)
                    .addComponent(btn_Loading))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ban01, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Ban02, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ban03, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Ban04, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Ban05, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(btn_Loading)
                .addGap(46, 46, 46))
        );

        panel_control_CTHD.setBackground(new java.awt.Color(204, 255, 255));
        panel_control_CTHD.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_control_CTHD, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_control_CTHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTrangThaiDaDat(JButton btn) {
        btn.setBackground(Color.YELLOW);
    }

    public void setTrangThaiTrong(JButton btn) {
        btn.setBackground(Color.GREEN);
    }

    public void setTrangThaiCoKhach(JButton btn) {
        btn.setBackground(Color.RED);
    }

    public void UpdateTrangThaiCoKhach(String maBan) {
        ban_BLL.CapNhatTrangThai(maBan, "hetcho");
        LoadTrangThaiBan();
    }

    public void UpdateTrangThaiVangKhach(String maBan) {
        ban_BLL.CapNhatTrangThai(maBan, "trong");
        LoadTrangThaiBan();
    }
    private void btn_Ban01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban01ActionPerformed

        Panel_ChiTietHD_Ban CT_HD_ban = new Panel_ChiTietHD_Ban();
        String MaBan = "B001";
        String ttBan = "bàn số 01";
        chirl_panel = CT_HD_ban;
        CT_HD_ban.setTenBan(ttBan);
        String trangthai = ban_BLL.getTrangThai(MaBan);
        CT_HD_ban.SetMaBan(MaBan, trangthai);
        if (trangthai != "trong") {
            CT_HD_ban.SetMaHoaDon(hoadon_bll.getMaHoaDonByBan(MaBan));
        }
        CT_HD_ban.LoadChiTietHoaDon();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
    }//GEN-LAST:event_btn_Ban01ActionPerformed

    private void btn_Ban02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban02ActionPerformed

        // TODO add your handling code here:
        Panel_ChiTietHD_Ban CT_HD_ban = new Panel_ChiTietHD_Ban();
        String MaBan = "B002";
        String ttBan = "bàn số 02";
        chirl_panel = CT_HD_ban;        
        CT_HD_ban.setTenBan(ttBan);
        String trangthai = ban_BLL.getTrangThai(MaBan);
        CT_HD_ban.SetMaBan(MaBan, trangthai);
        if (trangthai != "trong") {
            CT_HD_ban.SetMaHoaDon(hoadon_bll.getMaHoaDonByBan(MaBan));
        }
        CT_HD_ban.LoadChiTietHoaDon();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();

    }//GEN-LAST:event_btn_Ban02ActionPerformed

    private void btn_Ban03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban03ActionPerformed

        // TODO add your handling code here:
        Panel_ChiTietHD_Ban CT_HD_ban = new Panel_ChiTietHD_Ban();
        String MaBan = "B003";
        String ttBan = "bàn số 03";
        chirl_panel = CT_HD_ban;
        CT_HD_ban.setTenBan(ttBan);
        String trangthai = ban_BLL.getTrangThai(MaBan);
        CT_HD_ban.SetMaBan(MaBan, trangthai);
        if (trangthai != "trong") {
            CT_HD_ban.SetMaHoaDon(hoadon_bll.getMaHoaDonByBan(MaBan));
        }
        CT_HD_ban.LoadChiTietHoaDon();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
    }//GEN-LAST:event_btn_Ban03ActionPerformed

    private void btn_LoadingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LoadingActionPerformed
        // TODO add your handling code here:
        LoadTrangThaiBan();
    }//GEN-LAST:event_btn_LoadingActionPerformed

    private void btn_Ban05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban05ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Panel_ChiTietHD_Ban CT_HD_ban = new Panel_ChiTietHD_Ban();
        String MaBan = "B005";
        String ttBan = "bàn số 05";
        chirl_panel = CT_HD_ban;
        CT_HD_ban.setTenBan(ttBan);
        String trangthai = ban_BLL.getTrangThai(MaBan);
        CT_HD_ban.SetMaBan(MaBan, trangthai);
        if (trangthai != "trong") {
            CT_HD_ban.SetMaHoaDon(hoadon_bll.getMaHoaDonByBan(MaBan));
        }
        CT_HD_ban.LoadChiTietHoaDon();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
    }//GEN-LAST:event_btn_Ban05ActionPerformed

    private void btn_Ban04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban04ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        Panel_ChiTietHD_Ban CT_HD_ban = new Panel_ChiTietHD_Ban();
        String MaBan = "B004";
        String ttBan = "bàn số 04";
        chirl_panel = CT_HD_ban;
        CT_HD_ban.setTenBan(ttBan);
        String trangthai = ban_BLL.getTrangThai(MaBan);
        CT_HD_ban.SetMaBan(MaBan, trangthai);
        if (trangthai != "trong") {
            CT_HD_ban.SetMaHoaDon(hoadon_bll.getMaHoaDonByBan(MaBan));
        }
        CT_HD_ban.LoadChiTietHoaDon();
        chirl_panel.removeAll();
        panel_control_CTHD.removeAll();
        panel_control_CTHD.add(chirl_panel);
        panel_control_CTHD.validate();
    }//GEN-LAST:event_btn_Ban04ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_QuanLyBan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_QuanLyBan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ban01;
    private javax.swing.JButton btn_Ban02;
    private javax.swing.JButton btn_Ban03;
    private javax.swing.JButton btn_Ban04;
    private javax.swing.JButton btn_Ban05;
    private javax.swing.JButton btn_Loading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel_control_CTHD;
    // End of variables declaration//GEN-END:variables
}
