/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.*;
import BLL.PHIEUNHAP_BLL;
import Connect.Connect_DB;
import DTO.*;
import DTO.PHIEUNHAP_DTO;
import BLL.PHIEUNHAP_BLL;
import java.sql.Connection;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


import javax.swing.JPanel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author caoth
 */
public class NhapHang extends javax.swing.JFrame {

    /**
     * Creates new form NhapHang
     */
    PHIEUNHAP_BLL phieuBLL=new PHIEUNHAP_BLL();
    //PHIEUNHAP_DTO n= new PHIEUNHAP_DTO();
            
            
    JPanel paneITem = new JPanel();
    public NhapHang() {
        initComponents();
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_nhacc = new javax.swing.JButton();
        btn_nguyenlieu = new javax.swing.JButton();
        btn_phieunhap = new javax.swing.JButton();
        panel_tonghop = new javax.swing.JPanel();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("QUẢN LÝ NHẬP HÀNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel2)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_nhacc.setBackground(new java.awt.Color(102, 204, 255));
        btn_nhacc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nhacc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nhacungcap.png"))); // NOI18N
        btn_nhacc.setText("NHÀ CUNG CẤP");
        btn_nhacc.setAlignmentY(0.0F);
        btn_nhacc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_nhacc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nhacc.setIconTextGap(15);
        btn_nhacc.setMaximumSize(null);
        btn_nhacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nhaccActionPerformed(evt);
            }
        });

        btn_nguyenlieu.setBackground(new java.awt.Color(102, 204, 255));
        btn_nguyenlieu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_nguyenlieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/nguyenlieu.png"))); // NOI18N
        btn_nguyenlieu.setText("NGUYÊN LIỆU");
        btn_nguyenlieu.setAlignmentY(0.0F);
        btn_nguyenlieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_nguyenlieu.setDoubleBuffered(true);
        btn_nguyenlieu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_nguyenlieu.setIconTextGap(15);
        btn_nguyenlieu.setMaximumSize(null);
        btn_nguyenlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nguyenlieuActionPerformed(evt);
            }
        });

        btn_phieunhap.setBackground(new java.awt.Color(102, 204, 255));
        btn_phieunhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_phieunhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phieunhaphang.png"))); // NOI18N
        btn_phieunhap.setText("PHIẾU NHẬP HÀNG");
        btn_phieunhap.setAlignmentY(0.0F);
        btn_phieunhap.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_phieunhap.setDoubleBuffered(true);
        btn_phieunhap.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_phieunhap.setIconTextGap(15);
        btn_phieunhap.setMaximumSize(null);
        btn_phieunhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_phieunhapActionPerformed(evt);
            }
        });

        panel_tonghop.setBackground(new java.awt.Color(204, 255, 204));
        panel_tonghop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_tonghop.setLayout(new java.awt.BorderLayout());

        btn_thoat.setBackground(new java.awt.Color(102, 204, 255));
        btn_thoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/thoat.png"))); // NOI18N
        btn_thoat.setText("THOÁT");
        btn_thoat.setAlignmentY(0.0F);
        btn_thoat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_thoat.setDoubleBuffered(true);
        btn_thoat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_thoat.setIconTextGap(15);
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nguyenlieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nhacc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_phieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(panel_tonghop, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btn_nhacc, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_nguyenlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_phieunhap, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
            .addComponent(panel_tonghop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nhaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nhaccActionPerformed
       
       // goi panel       
       Panel_NhaCungCap pnNCC = new Panel_NhaCungCap();
       paneITem = pnNCC;
       panel_tonghop.removeAll();
       panel_tonghop.add(paneITem);
       panel_tonghop.validate();
    }//GEN-LAST:event_btn_nhaccActionPerformed

    private void btn_phieunhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_phieunhapActionPerformed
        // TODO add your handling code here:
        
       Panel_PhieuNhap pnPN = new Panel_PhieuNhap();
       paneITem = pnPN;
       panel_tonghop.removeAll();
       panel_tonghop.add(paneITem);
       panel_tonghop.validate();
       
       
    }//GEN-LAST:event_btn_phieunhapActionPerformed

    private void btn_nguyenlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nguyenlieuActionPerformed
        // TODO add your handling code here:
       Panel_NguyenLieu pnNL = new Panel_NguyenLieu();
       paneITem = pnNL;
       panel_tonghop.removeAll();
       panel_tonghop.add(paneITem);
       panel_tonghop.validate();
    }//GEN-LAST:event_btn_nguyenlieuActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Bạn có muốn thoát","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) System.exit(0);

    }//GEN-LAST:event_btn_thoatActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_nguyenlieu;
    private javax.swing.JButton btn_nhacc;
    private javax.swing.JButton btn_phieunhap;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_tonghop;
    // End of variables declaration//GEN-END:variables
}
